# lightning:
#   trainer:
#     plugins: [DDPPlugin(find_unused_parameters=False)]

model:
  base_learning_rate: 4.5e-6
  target: model.model.Classification
  params:  # change to your own parameters
      model:
          target: module.transformer.TransformerPredictor
          params:
              model_dim: 224
              num_layers: 1
              num_head: 4
              num_classes: 2
              input_dim: 1
              num_data: 9

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 8
    train:
      target: data.custom.TransformerTrain
      params:
        training_file: data/datasets/data_nozero.csv
    validation:
      target: data.custom.TransformerTest
      params:
        test_file: data/datasets/data_nozero.csv
